#!/usr/bin/env python3

"""
A mini-tool for easily previewing blobs in cloud storage from the command-line

requirements:
- python3
- pillow (for loading images)
- gsutil, properly configured (to download gcloud data)
- pyplot (optionnal, for a better image viewer)

installation / usage:
- Move this file in your /usr/local/bin/ folder
- example use:
    gs_preview gs://cilex-solidify-datasets/wUCFNRsXkmhekrnrUHGh/images/000243af2784583ded7d03b98d74b949.jpg
"""

from PIL import Image
import subprocess
from tempfile import NamedTemporaryFile
import sys
import os
import subprocess, sys
import pydoc

def main():
  with NamedTemporaryFile() as file:
    # Download file in a temp location (we'll delete it as soon as we're finished)
    subprocess.run(f"gsutil cp {sys.argv[1]} {file.name}", shell=True, check=True)

    try:
      openImage(file.name)
    except:
      with open(file.name) as f:
        pydoc.pager(f.read())

def openImage(filePath):
  im = Image.open(filePath)
  try:
    # Try using the better "pyplot" viewer, if it's available
    from matplotlib import pyplot as plt
    import matplotlib

    # Remove margins, ticks and others
    matplotlib.rcParams['savefig.pad_inches'] = 0
    ax = plt.axes([0,0,1,1], frameon=False)
    ax.get_xaxis().set_visible(False)
    ax.get_yaxis().set_visible(False)
    plt.autoscale(tight=True)

    ax.imshow(im)
    plt.show()
  except ImportError:
    # fall back to the basic pillow image viewer
    im.show()

main()
