#! /bin/bash

set -o nounset # error on unset variables
set -o errexit # exit on error


# install dependencies for building python
sudo apt-get update
sudo apt-get build-dep python3
sudo apt-get build-dep python2

sudo apt-get install build-essential gdb lcov pkg-config \
      libbz2-dev libffi-dev libgdbm-dev libgdbm-compat-dev liblzma-dev \
      libncurses5-dev libreadline6-dev libsqlite3-dev libssl-dev \
      lzma lzma-dev tk-dev uuid-dev zlib1g-dev

cd /opt
sudo wget https://www.python.org/ftp/python/$1/Python-$1.tgz
sudo tar xzf Python-$1.tgz


cd Python-$1
sudo ./configure --enable-optimizations
sudo make -j altinstall

# cleanup
cd /opt
sudo rm Python-$1.tgz Python-$1

echo "successfully installed python $1"
