#!/bin/bash
# Convert to mp4, with sensible default settings. Requires ffmpeg

name=${1%.*}

ffmpeg -i "${1}" \
  -pix_fmt yuv420p \
  -vcodec libx265 \
  -crf 28 \
  -tag:v hvc1 \
  -profile:v main \
  -movflags +faststart \
  "${name}_converted.mp4"
  # -vf "scale='min(720,iw)':-2" \
