#!/bin/bash

# Custom bash profile aliases and config
# loaded from .bashrc

############ edit aliases ############
# edit this file
alias editaliases="vim ~/.bashrc_custom && reloadaliases"
# reload this file
alias reloadaliases="source ~/.bashrc_custom"



############ virtual env ############
# create and activate a virtualenv
alias makeenv="python3 -m venv env && activateenv"
alias makeenv2.7="virtualenv --python=/usr/bin/python2.7 env && activateenv"
alias makeenv3.6="python3.6 -m venv env && activateenv"

# activate the virtualenv in the current directory
alias activateenv="source env/bin/activate"

# deactivate and delete a virtualenv
alias deleteenv="deactivate > /dev/null 2>&1; rm -rf env/"

# delete, recreate and reinstall a virtualenv
alias resetenv="deleteenv && makeenv && pip install -r requirements.txt"

# activate the virtualenv in the current directory
alias activateenv="source env/bin/activate"



############ enable custom commands ############
export PATH=~/unix-setup/commands:$PATH


############ colors ############
RED="\033[0;31m"
YELLOW="\033[1;33m"
BLUE="\033[1;34m"
PURPLE="\033[1;35m"
CYAN="\033[1;36m"
NC="\033[0m"

############ custom prompt ############
alias prompt-minimal="export PS1='$BLUE>$NC '"
alias prompt-small="export PS1='$BLUE$(whoami) [$(uname)]$NC > '"
alias prompt-full="export PS1='[$(uname)] $BLUE$(whoami)@$(hostname) $PURPLE \w$NC\n> '"
prompt-full



############ various ############
alias open="xdg-open"
alias lh="ls -lah"
